// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-courses.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_courses_default = defineTool({
  name: "list_courses",
  title: "List courses",
  description: "List courses owned by the signed-in EduGen AI user.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max courses to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("courses").select("id, title, description, status, created_at, updated_at").eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { courses: data }
    };
  }
});

// src/lib/mcp/tools/get-course.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_course_default = defineTool2({
  name: "get_course",
  title: "Get course",
  description: "Fetch a course with its modules for the signed-in user.",
  inputSchema: {
    course_id: z2.string().uuid().describe("UUID of the course to load.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ course_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    const { data: course, error: cErr } = await sb.from("courses").select("id, title, description, status, created_at, updated_at, user_id").eq("id", course_id).maybeSingle();
    if (cErr) return { content: [{ type: "text", text: cErr.message }], isError: true };
    if (!course) return { content: [{ type: "text", text: "Course not found" }], isError: true };
    const { data: modules, error: mErr } = await sb.from("course_modules").select("id, title, content, order_index").eq("course_id", course_id).order("order_index", { ascending: true });
    if (mErr) return { content: [{ type: "text", text: mErr.message }], isError: true };
    const payload = { course, modules: modules ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/search-courses.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_courses_default = defineTool3({
  name: "search_courses",
  title: "Search courses",
  description: "Search the signed-in user's courses by title or description.",
  inputSchema: {
    query: z3.string().trim().min(1).describe("Text to search in course title/description."),
    limit: z3.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    const like = `%${query.replace(/[%_]/g, "")}%`;
    const { data, error } = await sb.from("courses").select("id, title, description, status, updated_at").eq("user_id", ctx.getUserId()).or(`title.ilike.${like},description.ilike.${like}`).order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { courses: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hhlzaryhsyqbqktxdgyb";
var mcp_default = defineMcp({
  name: "edugen-ai-mcp",
  title: "EduGen AI",
  version: "0.1.0",
  instructions: "Tools for EduGen AI. Use `list_courses` to browse the signed-in user's courses, `search_courses` to find one by keyword, and `get_course` to load a course with its modules.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_courses_default, search_courses_default, get_course_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
